'use client'

import { useState } from 'react'
import { Lightbulb, Users, ChevronRight, ChevronDown, Sparkles } from 'lucide-react'
import { aiRecommendations } from '@/lib/types'
import { cn } from '@/lib/utils'

const priorityConfig = {
  high: { bg: 'bg-danger/10 border-danger/20', badge: 'bg-danger/15 text-danger', dot: 'bg-danger' },
  medium: { bg: 'bg-warning/10 border-warning/20', badge: 'bg-warning/15 text-warning', dot: 'bg-warning' },
  low: { bg: 'bg-success/10 border-success/20', badge: 'bg-success/15 text-success', dot: 'bg-success' },
}

export function HRRecommendations() {
  const [expanded, setExpanded] = useState<string | null>('r1')

  const highPriority = aiRecommendations.filter((r) => r.priority === 'high')
  const medPriority = aiRecommendations.filter((r) => r.priority === 'medium')
  const lowPriority = aiRecommendations.filter((r) => r.priority === 'low')

  function RecommendationCard({ rec }: { rec: (typeof aiRecommendations)[0] }) {
    const { bg, badge, dot } = priorityConfig[rec.priority]
    const isOpen = expanded === rec.id
    return (
      <div className={cn('rounded-xl border overflow-hidden transition-all', isOpen ? bg : 'bg-card border-border')}>
        <button
          onClick={() => setExpanded(isOpen ? null : rec.id)}
          className="w-full flex items-start gap-4 p-4 text-left"
        >
          <div className={cn('mt-1 w-2 h-2 rounded-full shrink-0', dot)} />
          <div className="flex-1 min-w-0">
            <div className="flex items-start justify-between gap-3">
              <h3 className="text-sm font-semibold text-foreground leading-snug">{rec.title}</h3>
              <div className="flex items-center gap-2 shrink-0">
                <span className={cn('text-xs font-medium px-2.5 py-0.5 rounded-full capitalize', badge)}>
                  {rec.priority} priority
                </span>
                <ChevronDown className={cn('w-4 h-4 text-muted-foreground transition-transform', isOpen && 'rotate-180')} />
              </div>
            </div>
            <div className="flex items-center gap-3 mt-1.5 text-xs text-muted-foreground">
              <span className="bg-muted px-2 py-0.5 rounded">{rec.department}</span>
              <span>{rec.category}</span>
              <span className="flex items-center gap-1">
                <Users className="w-3 h-3" />
                {rec.affectedEmployees} employees
              </span>
            </div>
          </div>
        </button>

        {isOpen && (
          <div className="px-10 pb-4 space-y-3">
            <p className="text-sm text-muted-foreground leading-relaxed">{rec.description}</p>
            <div className="flex items-start gap-2 p-3 rounded-lg bg-brand/5 border border-brand/15">
              <ChevronRight className="w-4 h-4 text-brand mt-0.5 shrink-0" />
              <div>
                <p className="text-xs font-semibold text-brand mb-1">Recommended Action</p>
                <p className="text-xs text-muted-foreground leading-relaxed">{rec.action}</p>
              </div>
            </div>
            <div className="flex items-center gap-2 pt-1">
              <button className="text-xs px-3 py-1.5 rounded-lg bg-brand text-brand-foreground hover:opacity-90 transition-opacity">
                Mark as In Progress
              </button>
              <button className="text-xs px-3 py-1.5 rounded-lg bg-muted text-muted-foreground hover:text-foreground transition-colors">
                Dismiss
              </button>
            </div>
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-y-auto p-6 space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 className="text-xl font-semibold text-foreground">AI Recommendations</h1>
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-brand/10 border border-brand/20">
              <Sparkles className="w-3.5 h-3.5 text-brand" />
              <span className="text-xs text-brand font-medium">AI Analysis</span>
            </div>
          </div>
          <p className="text-sm text-muted-foreground">
            Generated by correlating self-report data with facility checklist gaps · April 2026
          </p>
        </div>
      </div>

      {/* AI context banner */}
      <div className="flex items-start gap-3 p-4 rounded-xl bg-brand/5 border border-brand/15">
        <Lightbulb className="w-4 h-4 text-brand mt-0.5 shrink-0" />
        <p className="text-xs text-muted-foreground leading-relaxed">
          <strong className="text-foreground">How this works.</strong> The AI engine correlates patterns in anonymized employee self-report data with facility checklist findings to surface prioritized, actionable recommendations. No individual employee data is included. Recommendations do not constitute legal compliance certification.
        </p>
      </div>

      {/* High priority */}
      {highPriority.length > 0 && (
        <div className="space-y-3">
          <h2 className="text-xs uppercase tracking-widest text-muted-foreground font-mono flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-danger inline-block" />
            High Priority · {highPriority.length} items
          </h2>
          {highPriority.map((r) => (
            <RecommendationCard key={r.id} rec={r} />
          ))}
        </div>
      )}

      {/* Medium priority */}
      {medPriority.length > 0 && (
        <div className="space-y-3">
          <h2 className="text-xs uppercase tracking-widest text-muted-foreground font-mono flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-warning inline-block" />
            Medium Priority · {medPriority.length} items
          </h2>
          {medPriority.map((r) => (
            <RecommendationCard key={r.id} rec={r} />
          ))}
        </div>
      )}

      {/* Low priority */}
      {lowPriority.length > 0 && (
        <div className="space-y-3">
          <h2 className="text-xs uppercase tracking-widest text-muted-foreground font-mono flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-success inline-block" />
            Low Priority · {lowPriority.length} items
          </h2>
          {lowPriority.map((r) => (
            <RecommendationCard key={r.id} rec={r} />
          ))}
        </div>
      )}
    </div>
  )
}
